# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'close_position_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_close_position(object):
    def setupUi(self, Dialog_close_position):
        Dialog_close_position.setObjectName("Dialog_close_position")
        Dialog_close_position.resize(221, 243)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog_close_position)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog_close_position)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_ProdCode = QtWidgets.QLineEdit(Dialog_close_position)
        self.lineEdit_ProdCode.setEnabled(False)
        self.lineEdit_ProdCode.setObjectName("lineEdit_ProdCode")
        self.horizontalLayout.addWidget(self.lineEdit_ProdCode)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog_close_position)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.spinBox_Price = QtWidgets.QSpinBox(Dialog_close_position)
        self.spinBox_Price.setEnabled(False)
        self.spinBox_Price.setMaximum(16777215)
        self.spinBox_Price.setObjectName("spinBox_Price")
        self.horizontalLayout_2.addWidget(self.spinBox_Price)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.checkBox_MarketOrder = QtWidgets.QCheckBox(Dialog_close_position)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkBox_MarketOrder.setFont(font)
        self.checkBox_MarketOrder.setChecked(True)
        self.checkBox_MarketOrder.setObjectName("checkBox_MarketOrder")
        self.horizontalLayout_6.addWidget(self.checkBox_MarketOrder)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog_close_position)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinBox_toler = QtWidgets.QSpinBox(Dialog_close_position)
        self.spinBox_toler.setObjectName("spinBox_toler")
        self.horizontalLayout_3.addWidget(self.spinBox_toler)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(Dialog_close_position)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.spinBox_Qty = QtWidgets.QSpinBox(Dialog_close_position)
        self.spinBox_Qty.setObjectName("spinBox_Qty")
        self.horizontalLayout_4.addWidget(self.spinBox_Qty)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(Dialog_close_position)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.comboBox_ValidType = QtWidgets.QComboBox(Dialog_close_position)
        self.comboBox_ValidType.setObjectName("comboBox_ValidType")
        self.comboBox_ValidType.addItem("")
        self.comboBox_ValidType.addItem("")
        self.comboBox_ValidType.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_ValidType)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.checkBox_OrderOptions = QtWidgets.QCheckBox(Dialog_close_position)
        self.checkBox_OrderOptions.setObjectName("checkBox_OrderOptions")
        self.horizontalLayout_7.addWidget(self.checkBox_OrderOptions)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_Long = QtWidgets.QPushButton(Dialog_close_position)
        self.pushButton_Long.setObjectName("pushButton_Long")
        self.horizontalLayout_8.addWidget(self.pushButton_Long)
        self.pushButton_Short = QtWidgets.QPushButton(Dialog_close_position)
        self.pushButton_Short.setObjectName("pushButton_Short")
        self.horizontalLayout_8.addWidget(self.pushButton_Short)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.label.setBuddy(self.lineEdit_ProdCode)
        self.label_2.setBuddy(self.spinBox_Price)
        self.label_3.setBuddy(self.spinBox_toler)
        self.label_4.setBuddy(self.spinBox_Qty)
        self.label_5.setBuddy(self.comboBox_ValidType)

        self.retranslateUi(Dialog_close_position)
        self.checkBox_MarketOrder.toggled['bool'].connect(self.spinBox_Price.setDisabled)
        self.checkBox_MarketOrder.toggled['bool'].connect(self.spinBox_toler.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog_close_position)

    def retranslateUi(self, Dialog_close_position):
        _translate = QtCore.QCoreApplication.translate
        Dialog_close_position.setWindowTitle(_translate("Dialog_close_position", "SP CLOSE POSITION"))
        self.label.setText(_translate("Dialog_close_position", "代码"))
        self.label_2.setText(_translate("Dialog_close_position", "价格"))
        self.spinBox_Price.setSpecialValueText(_translate("Dialog_close_position", "市场追价"))
        self.checkBox_MarketOrder.setText(_translate("Dialog_close_position", "市价"))
        self.label_3.setText(_translate("Dialog_close_position", "追价"))
        self.label_4.setText(_translate("Dialog_close_position", "数量"))
        self.label_5.setText(_translate("Dialog_close_position", "种类"))
        self.comboBox_ValidType.setItemText(0, _translate("Dialog_close_position", "即日"))
        self.comboBox_ValidType.setItemText(1, _translate("Dialog_close_position", "成交并取消"))
        self.comboBox_ValidType.setItemText(2, _translate("Dialog_close_position", "成交或取消"))
        self.checkBox_OrderOptions.setText(_translate("Dialog_close_position", "T+1"))
        self.pushButton_Long.setText(_translate("Dialog_close_position", "买入"))
        self.pushButton_Short.setText(_translate("Dialog_close_position", "沽出"))

