# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order_stoploss_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_order_stoploss(object):
    def setupUi(self, Dialog_order_stoploss):
        Dialog_order_stoploss.setObjectName("Dialog_order_stoploss")
        Dialog_order_stoploss.setEnabled(True)
        Dialog_order_stoploss.resize(510, 700)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(Dialog_order_stoploss)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(Dialog_order_stoploss)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_CondType = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_CondType.sizePolicy().hasHeightForWidth())
        self.label_CondType.setSizePolicy(sizePolicy)
        self.label_CondType.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CondType.setObjectName("label_CondType")
        self.horizontalLayout_6.addWidget(self.label_CondType)
        self.comboBox_CondType = QtWidgets.QComboBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_CondType.sizePolicy().hasHeightForWidth())
        self.comboBox_CondType.setSizePolicy(sizePolicy)
        self.comboBox_CondType.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBox_CondType.setMaximumSize(QtCore.QSize(90, 16777215))
        self.comboBox_CondType.setObjectName("comboBox_CondType")
        self.comboBox_CondType.addItem("")
        self.comboBox_CondType.addItem("")
        self.comboBox_CondType.addItem("")
        self.comboBox_CondType.addItem("")
        self.comboBox_CondType.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_CondType)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(90, 0))
        self.stackedWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(140, 90))
        self.groupBox.setMaximumSize(QtCore.QSize(170, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_ValidType = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ValidType.setObjectName("horizontalLayout_ValidType")
        self.label_ValidType = QtWidgets.QLabel(self.groupBox)
        self.label_ValidType.setObjectName("label_ValidType")
        self.horizontalLayout_ValidType.addWidget(self.label_ValidType)
        self.comboBox_ValidType = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_ValidType.sizePolicy().hasHeightForWidth())
        self.comboBox_ValidType.setSizePolicy(sizePolicy)
        self.comboBox_ValidType.setMinimumSize(QtCore.QSize(75, 0))
        self.comboBox_ValidType.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_ValidType.setTabletTracking(True)
        self.comboBox_ValidType.setObjectName("comboBox_ValidType")
        self.comboBox_ValidType.addItem("")
        self.comboBox_ValidType.addItem("")
        self.comboBox_ValidType.addItem("")
        self.comboBox_ValidType.addItem("")
        self.comboBox_ValidType.addItem("")
        self.horizontalLayout_ValidType.addWidget(self.comboBox_ValidType)
        self.verticalLayout_5.addLayout(self.horizontalLayout_ValidType)
        self.horizontalLayout_ValidTime = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ValidTime.setObjectName("horizontalLayout_ValidTime")
        self.label_ValidTime = QtWidgets.QLabel(self.groupBox)
        self.label_ValidTime.setObjectName("label_ValidTime")
        self.horizontalLayout_ValidTime.addWidget(self.label_ValidTime)
        self.dateEdit_ValidTime = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_ValidTime.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit_ValidTime.sizePolicy().hasHeightForWidth())
        self.dateEdit_ValidTime.setSizePolicy(sizePolicy)
        self.dateEdit_ValidTime.setMinimumSize(QtCore.QSize(75, 0))
        self.dateEdit_ValidTime.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dateEdit_ValidTime.setCalendarPopup(True)
        self.dateEdit_ValidTime.setDate(QtCore.QDate(1970, 1, 1))
        self.dateEdit_ValidTime.setObjectName("dateEdit_ValidTime")
        self.horizontalLayout_ValidTime.addWidget(self.dateEdit_ValidTime)
        self.verticalLayout_5.addLayout(self.horizontalLayout_ValidTime)
        self.verticalLayout_17.addLayout(self.verticalLayout_5)
        self.verticalLayout_18.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page)
        self.groupBox_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(140, 70))
        self.groupBox_2.setMaximumSize(QtCore.QSize(170, 16777215))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.checkBox_stop_tri = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_stop_tri.setEnabled(True)
        self.checkBox_stop_tri.setObjectName("checkBox_stop_tri")
        self.verticalLayout_15.addWidget(self.checkBox_stop_tri)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_StopType = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_StopType.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_StopType.sizePolicy().hasHeightForWidth())
        self.comboBox_StopType.setSizePolicy(sizePolicy)
        self.comboBox_StopType.setMinimumSize(QtCore.QSize(40, 0))
        self.comboBox_StopType.setMaximumSize(QtCore.QSize(80, 16777215))
        self.comboBox_StopType.setObjectName("comboBox_StopType")
        self.comboBox_StopType.addItem("")
        self.comboBox_StopType.addItem("")
        self.comboBox_StopType.addItem("")
        self.comboBox_StopType.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_StopType)
        self.spinBox_StopLevel = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_StopLevel.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_StopLevel.sizePolicy().hasHeightForWidth())
        self.spinBox_StopLevel.setSizePolicy(sizePolicy)
        self.spinBox_StopLevel.setMinimumSize(QtCore.QSize(70, 0))
        self.spinBox_StopLevel.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBox_StopLevel.setMaximum(2147483647)
        self.spinBox_StopLevel.setObjectName("spinBox_StopLevel")
        self.horizontalLayout_4.addWidget(self.spinBox_StopLevel)
        self.verticalLayout_15.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_15)
        self.verticalLayout_18.addWidget(self.groupBox_2)
        self.verticalLayout_10.addLayout(self.verticalLayout_18)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.radioButton_buy1 = QtWidgets.QRadioButton(self.page_2)
        self.radioButton_buy1.setEnabled(False)
        self.radioButton_buy1.setCheckable(True)
        self.radioButton_buy1.setChecked(False)
        self.radioButton_buy1.setObjectName("radioButton_buy1")
        self.horizontalLayout_11.addWidget(self.radioButton_buy1)
        self.radioButton_sell1 = QtWidgets.QRadioButton(self.page_2)
        self.radioButton_sell1.setEnabled(False)
        self.radioButton_sell1.setCheckable(True)
        self.radioButton_sell1.setObjectName("radioButton_sell1")
        self.horizontalLayout_11.addWidget(self.radioButton_sell1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.spinBox_StopLevel2 = QtWidgets.QSpinBox(self.page_2)
        self.spinBox_StopLevel2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_StopLevel2.sizePolicy().hasHeightForWidth())
        self.spinBox_StopLevel2.setSizePolicy(sizePolicy)
        self.spinBox_StopLevel2.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_StopLevel2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBox_StopLevel2.setMaximum(2147483647)
        self.spinBox_StopLevel2.setObjectName("spinBox_StopLevel2")
        self.horizontalLayout_12.addWidget(self.spinBox_StopLevel2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        self.spinBox_toler = QtWidgets.QSpinBox(self.page_2)
        self.spinBox_toler.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_toler.sizePolicy().hasHeightForWidth())
        self.spinBox_toler.setSizePolicy(sizePolicy)
        self.spinBox_toler.setMinimumSize(QtCore.QSize(40, 0))
        self.spinBox_toler.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_toler.setMaximum(16777215)
        self.spinBox_toler.setObjectName("spinBox_toler")
        self.horizontalLayout_13.addWidget(self.spinBox_toler)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.verticalLayout_11.addLayout(self.verticalLayout_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(140, 70))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 94, 46))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_Trailing_Stop = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_Trailing_Stop.setObjectName("checkBox_Trailing_Stop")
        self.verticalLayout_6.addWidget(self.checkBox_Trailing_Stop)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.spinBox_trailing_stop_step = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_trailing_stop_step.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_trailing_stop_step.sizePolicy().hasHeightForWidth())
        self.spinBox_trailing_stop_step.setSizePolicy(sizePolicy)
        self.spinBox_trailing_stop_step.setMinimumSize(QtCore.QSize(40, 0))
        self.spinBox_trailing_stop_step.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_trailing_stop_step.setMaximum(16777215)
        self.spinBox_trailing_stop_step.setObjectName("spinBox_trailing_stop_step")
        self.horizontalLayout_14.addWidget(self.spinBox_trailing_stop_step)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.verticalLayout_11.addWidget(self.groupBox_3)
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_buysell2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buysell2.setObjectName("horizontalLayout_buysell2")
        self.radioButton_buy2 = QtWidgets.QRadioButton(self.page_3)
        self.radioButton_buy2.setEnabled(False)
        self.radioButton_buy2.setCheckable(True)
        self.radioButton_buy2.setObjectName("radioButton_buy2")
        self.horizontalLayout_buysell2.addWidget(self.radioButton_buy2)
        self.radioButton_sell2 = QtWidgets.QRadioButton(self.page_3)
        self.radioButton_sell2.setEnabled(False)
        self.radioButton_sell2.setObjectName("radioButton_sell2")
        self.horizontalLayout_buysell2.addWidget(self.radioButton_sell2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_buysell2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_12 = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        self.spinBox_oco_StopLevel = QtWidgets.QSpinBox(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_oco_StopLevel.sizePolicy().hasHeightForWidth())
        self.spinBox_oco_StopLevel.setSizePolicy(sizePolicy)
        self.spinBox_oco_StopLevel.setMinimumSize(QtCore.QSize(75, 0))
        self.spinBox_oco_StopLevel.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBox_oco_StopLevel.setMaximum(2147483647)
        self.spinBox_oco_StopLevel.setObjectName("spinBox_oco_StopLevel")
        self.horizontalLayout_16.addWidget(self.spinBox_oco_StopLevel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_13 = QtWidgets.QLabel(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_17.addWidget(self.label_13)
        self.spinBox_oco_toler = QtWidgets.QSpinBox(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_oco_toler.sizePolicy().hasHeightForWidth())
        self.spinBox_oco_toler.setSizePolicy(sizePolicy)
        self.spinBox_oco_toler.setMinimumSize(QtCore.QSize(40, 0))
        self.spinBox_oco_toler.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_oco_toler.setMaximum(16777215)
        self.spinBox_oco_toler.setObjectName("spinBox_oco_toler")
        self.horizontalLayout_17.addWidget(self.spinBox_oco_toler)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.verticalLayout_13.addLayout(self.verticalLayout_3)
        self.label_oco_pirce = QtWidgets.QLabel(self.page_3)
        self.label_oco_pirce.setText("")
        self.label_oco_pirce.setObjectName("label_oco_pirce")
        self.verticalLayout_13.addWidget(self.label_oco_pirce)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.page_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.spinBox_market_level = QtWidgets.QSpinBox(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_market_level.sizePolicy().hasHeightForWidth())
        self.spinBox_market_level.setSizePolicy(sizePolicy)
        self.spinBox_market_level.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_market_level.setMaximum(16777215)
        self.spinBox_market_level.setObjectName("spinBox_market_level")
        self.horizontalLayout_3.addWidget(self.spinBox_market_level)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_14 = QtWidgets.QLabel(self.page_4)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_18.addWidget(self.label_14)
        self.spinBox_bullbear_profit = QtWidgets.QSpinBox(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_bullbear_profit.sizePolicy().hasHeightForWidth())
        self.spinBox_bullbear_profit.setSizePolicy(sizePolicy)
        self.spinBox_bullbear_profit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_bullbear_profit.setMaximum(16777215)
        self.spinBox_bullbear_profit.setObjectName("spinBox_bullbear_profit")
        self.horizontalLayout_18.addWidget(self.spinBox_bullbear_profit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_15 = QtWidgets.QLabel(self.page_4)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_19.addWidget(self.label_15)
        self.spinBox_bullbear_loss = QtWidgets.QSpinBox(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_bullbear_loss.sizePolicy().hasHeightForWidth())
        self.spinBox_bullbear_loss.setSizePolicy(sizePolicy)
        self.spinBox_bullbear_loss.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_bullbear_loss.setMaximum(16777215)
        self.spinBox_bullbear_loss.setObjectName("spinBox_bullbear_loss")
        self.horizontalLayout_19.addWidget(self.spinBox_bullbear_loss)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_16 = QtWidgets.QLabel(self.page_4)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_20.addWidget(self.label_16)
        self.spinBox_bullbear_loss_toler = QtWidgets.QSpinBox(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_bullbear_loss_toler.sizePolicy().hasHeightForWidth())
        self.spinBox_bullbear_loss_toler.setSizePolicy(sizePolicy)
        self.spinBox_bullbear_loss_toler.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_bullbear_loss_toler.setMaximum(16777215)
        self.spinBox_bullbear_loss_toler.setObjectName("spinBox_bullbear_loss_toler")
        self.horizontalLayout_20.addWidget(self.spinBox_bullbear_loss_toler)
        self.verticalLayout_4.addLayout(self.horizontalLayout_20)
        self.verticalLayout_14.addLayout(self.verticalLayout_4)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.dateTimeEdit_sched_time = QtWidgets.QDateTimeEdit(self.page_5)
        self.dateTimeEdit_sched_time.setDate(QtCore.QDate(2018, 4, 20))
        self.dateTimeEdit_sched_time.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2050, 12, 31), QtCore.QTime(23, 59, 59)))
        self.dateTimeEdit_sched_time.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit_sched_time.setCalendarPopup(True)
        self.dateTimeEdit_sched_time.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateTimeEdit_sched_time.setObjectName("dateTimeEdit_sched_time")
        self.verticalLayout_9.addWidget(self.dateTimeEdit_sched_time)
        self.stackedWidget.addWidget(self.page_5)
        self.verticalLayout_8.addWidget(self.stackedWidget)
        self.gridLayout.addLayout(self.verticalLayout_8, 0, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox_account = QtWidgets.QComboBox(self.tab)
        self.comboBox_account.setObjectName("comboBox_account")
        self.horizontalLayout_2.addWidget(self.comboBox_account)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout__ProdCode = QtWidgets.QHBoxLayout()
        self.horizontalLayout__ProdCode.setObjectName("horizontalLayout__ProdCode")
        self.label__ProdCode = QtWidgets.QLabel(self.tab)
        self.label__ProdCode.setObjectName("label__ProdCode")
        self.horizontalLayout__ProdCode.addWidget(self.label__ProdCode)
        self.lineEdit_ProdCode = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ProdCode.sizePolicy().hasHeightForWidth())
        self.lineEdit_ProdCode.setSizePolicy(sizePolicy)
        self.lineEdit_ProdCode.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_ProdCode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_ProdCode.setObjectName("lineEdit_ProdCode")
        self.horizontalLayout__ProdCode.addWidget(self.lineEdit_ProdCode)
        self.checkBox_lock = QtWidgets.QCheckBox(self.tab)
        self.checkBox_lock.setTristate(False)
        self.checkBox_lock.setObjectName("checkBox_lock")
        self.horizontalLayout__ProdCode.addWidget(self.checkBox_lock)
        self.verticalLayout.addLayout(self.horizontalLayout__ProdCode)
        self.horizontalLayout_Price = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Price.setObjectName("horizontalLayout_Price")
        self.label_Price = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Price.sizePolicy().hasHeightForWidth())
        self.label_Price.setSizePolicy(sizePolicy)
        self.label_Price.setObjectName("label_Price")
        self.horizontalLayout_Price.addWidget(self.label_Price)
        self.spinBox_Price = QtWidgets.QSpinBox(self.tab)
        self.spinBox_Price.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Price.sizePolicy().hasHeightForWidth())
        self.spinBox_Price.setSizePolicy(sizePolicy)
        self.spinBox_Price.setMinimumSize(QtCore.QSize(65, 0))
        self.spinBox_Price.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBox_Price.setMaximum(2147483647)
        self.spinBox_Price.setObjectName("spinBox_Price")
        self.horizontalLayout_Price.addWidget(self.spinBox_Price)
        self.verticalLayout.addLayout(self.horizontalLayout_Price)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_Auction = QtWidgets.QCheckBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Auction.sizePolicy().hasHeightForWidth())
        self.checkBox_Auction.setSizePolicy(sizePolicy)
        self.checkBox_Auction.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_Auction.setObjectName("checkBox_Auction")
        self.horizontalLayout_5.addWidget(self.checkBox_Auction)
        self.checkBox_Market = QtWidgets.QCheckBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_Market.sizePolicy().hasHeightForWidth())
        self.checkBox_Market.setSizePolicy(sizePolicy)
        self.checkBox_Market.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox_Market.setObjectName("checkBox_Market")
        self.horizontalLayout_5.addWidget(self.checkBox_Market)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_Qty = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Qty.setObjectName("horizontalLayout_Qty")
        self.label_Qty = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Qty.sizePolicy().hasHeightForWidth())
        self.label_Qty.setSizePolicy(sizePolicy)
        self.label_Qty.setObjectName("label_Qty")
        self.horizontalLayout_Qty.addWidget(self.label_Qty)
        self.spinBox_Qty = QtWidgets.QSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_Qty.sizePolicy().hasHeightForWidth())
        self.spinBox_Qty.setSizePolicy(sizePolicy)
        self.spinBox_Qty.setMinimumSize(QtCore.QSize(40, 0))
        self.spinBox_Qty.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_Qty.setMaximum(16777215)
        self.spinBox_Qty.setProperty("value", 1)
        self.spinBox_Qty.setObjectName("spinBox_Qty")
        self.horizontalLayout_Qty.addWidget(self.spinBox_Qty)
        self.verticalLayout.addLayout(self.horizontalLayout_Qty)
        self.horizontalLayout_buysell = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buysell.setObjectName("horizontalLayout_buysell")
        self.pushButton_buy = QtWidgets.QPushButton(self.tab)
        self.pushButton_buy.setEnabled(False)
        self.pushButton_buy.setObjectName("pushButton_buy")
        self.horizontalLayout_buysell.addWidget(self.pushButton_buy)
        self.pushButton_sell = QtWidgets.QPushButton(self.tab)
        self.pushButton_sell.setEnabled(False)
        self.pushButton_sell.setObjectName("pushButton_sell")
        self.horizontalLayout_buysell.addWidget(self.pushButton_sell)
        self.verticalLayout.addLayout(self.horizontalLayout_buysell)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_Ref = QtWidgets.QLabel(self.tab)
        self.label_Ref.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ref.setObjectName("label_Ref")
        self.horizontalLayout.addWidget(self.label_Ref)
        self.lineEdit_Ref = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Ref.sizePolicy().hasHeightForWidth())
        self.lineEdit_Ref.setSizePolicy(sizePolicy)
        self.lineEdit_Ref.setMinimumSize(QtCore.QSize(65, 0))
        self.lineEdit_Ref.setObjectName("lineEdit_Ref")
        self.horizontalLayout.addWidget(self.lineEdit_Ref)
        self.checkBox_OrderOptions = QtWidgets.QCheckBox(self.tab)
        self.checkBox_OrderOptions.setObjectName("checkBox_OrderOptions")
        self.horizontalLayout.addWidget(self.checkBox_OrderOptions)
        self.checkBox_invalid = QtWidgets.QCheckBox(self.tab)
        self.checkBox_invalid.setObjectName("checkBox_invalid")
        self.horizontalLayout.addWidget(self.checkBox_invalid)
        self.checkBox_order_assistant = QtWidgets.QCheckBox(self.tab)
        self.checkBox_order_assistant.setObjectName("checkBox_order_assistant")
        self.horizontalLayout.addWidget(self.checkBox_order_assistant)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 4)
        self.horizontalLayout_7.addLayout(self.gridLayout)
        self.verticalLayout_23.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.lineEdit_prodcode = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_prodcode.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lineEdit_prodcode.setReadOnly(True)
        self.lineEdit_prodcode.setObjectName("lineEdit_prodcode")
        self.horizontalLayout_10.addWidget(self.lineEdit_prodcode)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.verticalLayout_16.addLayout(self.horizontalLayout_15)
        self.groupBox_quick_sl = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_quick_sl.sizePolicy().hasHeightForWidth())
        self.groupBox_quick_sl.setSizePolicy(sizePolicy)
        self.groupBox_quick_sl.setObjectName("groupBox_quick_sl")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_quick_sl)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.radioButton_holding = QtWidgets.QRadioButton(self.groupBox_quick_sl)
        self.radioButton_holding.setText("")
        self.radioButton_holding.setChecked(True)
        self.radioButton_holding.setObjectName("radioButton_holding")
        self.horizontalLayout_21.addWidget(self.radioButton_holding)
        self.label_3 = QtWidgets.QLabel(self.groupBox_quick_sl)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_21.addWidget(self.label_3)
        self.lineEdit_hodling_pos = QtWidgets.QLineEdit(self.groupBox_quick_sl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_hodling_pos.sizePolicy().hasHeightForWidth())
        self.lineEdit_hodling_pos.setSizePolicy(sizePolicy)
        self.lineEdit_hodling_pos.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_hodling_pos.setReadOnly(True)
        self.lineEdit_hodling_pos.setObjectName("lineEdit_hodling_pos")
        self.horizontalLayout_21.addWidget(self.lineEdit_hodling_pos)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem2)
        self.verticalLayout_20.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.radioButton_session = QtWidgets.QRadioButton(self.groupBox_quick_sl)
        self.radioButton_session.setText("")
        self.radioButton_session.setObjectName("radioButton_session")
        self.horizontalLayout_22.addWidget(self.radioButton_session)
        self.label_4 = QtWidgets.QLabel(self.groupBox_quick_sl)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_22.addWidget(self.label_4)
        self.lineEdit_session_pos = QtWidgets.QLineEdit(self.groupBox_quick_sl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_session_pos.sizePolicy().hasHeightForWidth())
        self.lineEdit_session_pos.setSizePolicy(sizePolicy)
        self.lineEdit_session_pos.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_session_pos.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_session_pos.setReadOnly(True)
        self.lineEdit_session_pos.setObjectName("lineEdit_session_pos")
        self.horizontalLayout_22.addWidget(self.lineEdit_session_pos)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem3)
        self.verticalLayout_20.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.radioButton_all = QtWidgets.QRadioButton(self.groupBox_quick_sl)
        self.radioButton_all.setText("")
        self.radioButton_all.setObjectName("radioButton_all")
        self.horizontalLayout_23.addWidget(self.radioButton_all)
        self.label_5 = QtWidgets.QLabel(self.groupBox_quick_sl)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_23.addWidget(self.label_5)
        self.lineEdit_all_pos = QtWidgets.QLineEdit(self.groupBox_quick_sl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_all_pos.sizePolicy().hasHeightForWidth())
        self.lineEdit_all_pos.setSizePolicy(sizePolicy)
        self.lineEdit_all_pos.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_all_pos.setReadOnly(True)
        self.lineEdit_all_pos.setObjectName("lineEdit_all_pos")
        self.horizontalLayout_23.addWidget(self.lineEdit_all_pos)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem4)
        self.verticalLayout_20.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_9.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_6 = QtWidgets.QLabel(self.groupBox_quick_sl)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_25.addWidget(self.label_6)
        self.spinBox_sl_toler = QtWidgets.QSpinBox(self.groupBox_quick_sl)
        self.spinBox_sl_toler.setObjectName("spinBox_sl_toler")
        self.horizontalLayout_25.addWidget(self.spinBox_sl_toler)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_8 = QtWidgets.QLabel(self.groupBox_quick_sl)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_26.addWidget(self.label_8)
        self.spinBox_stoploss_addtion = QtWidgets.QSpinBox(self.groupBox_quick_sl)
        self.spinBox_stoploss_addtion.setMaximum(1000)
        self.spinBox_stoploss_addtion.setProperty("value", 50)
        self.spinBox_stoploss_addtion.setObjectName("spinBox_stoploss_addtion")
        self.horizontalLayout_26.addWidget(self.spinBox_stoploss_addtion)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_17 = QtWidgets.QLabel(self.groupBox_quick_sl)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_27.addWidget(self.label_17)
        self.spinBox_lock = QtWidgets.QSpinBox(self.groupBox_quick_sl)
        self.spinBox_lock.setObjectName("spinBox_lock")
        self.horizontalLayout_27.addWidget(self.spinBox_lock)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_27)
        self.verticalLayout_21.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.pushButton_stoploss = QtWidgets.QPushButton(self.groupBox_quick_sl)
        self.pushButton_stoploss.setObjectName("pushButton_stoploss")
        self.horizontalLayout_28.addWidget(self.pushButton_stoploss)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem5)
        self.verticalLayout_21.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_9.addLayout(self.verticalLayout_21)
        self.verticalLayout_19.addLayout(self.horizontalLayout_9)
        self.verticalLayout_16.addWidget(self.groupBox_quick_sl)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.pushButton_del_all_orders = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_del_all_orders.setObjectName("pushButton_del_all_orders")
        self.horizontalLayout_29.addWidget(self.pushButton_del_all_orders)
        self.pushButton_del_long_sl = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_del_long_sl.setObjectName("pushButton_del_long_sl")
        self.horizontalLayout_29.addWidget(self.pushButton_del_long_sl)
        self.pushButton_del_short_sl = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_del_short_sl.setObjectName("pushButton_del_short_sl")
        self.horizontalLayout_29.addWidget(self.pushButton_del_short_sl)
        self.pushButton_del_remain_sl = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_del_remain_sl.setObjectName("pushButton_del_remain_sl")
        self.horizontalLayout_29.addWidget(self.pushButton_del_remain_sl)
        self.verticalLayout_16.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30.addLayout(self.verticalLayout_16)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_8.addWidget(self.tabWidget)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_24.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.groupBox_price = QtWidgets.QGroupBox(Dialog_order_stoploss)
        self.groupBox_price.setCheckable(True)
        self.groupBox_price.setChecked(False)
        self.groupBox_price.setObjectName("groupBox_price")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.groupBox_price)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.tableWidget_bid_ask = QtWidgets.QTableWidget(self.groupBox_price)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_bid_ask.sizePolicy().hasHeightForWidth())
        self.tableWidget_bid_ask.setSizePolicy(sizePolicy)
        self.tableWidget_bid_ask.setMaximumSize(QtCore.QSize(200, 305))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget_bid_ask.setFont(font)
        self.tableWidget_bid_ask.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_bid_ask.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_bid_ask.setAutoScrollMargin(16)
        self.tableWidget_bid_ask.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_bid_ask.setColumnCount(2)
        self.tableWidget_bid_ask.setObjectName("tableWidget_bid_ask")
        self.tableWidget_bid_ask.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_bid_ask.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_bid_ask.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_bid_ask.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_bid_ask.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_bid_ask.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_bid_ask.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_bid_ask.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_bid_ask.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_bid_ask.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_bid_ask.setVerticalHeaderItem(9, item)
        self.tableWidget_bid_ask.horizontalHeader().setVisible(False)
        self.tableWidget_bid_ask.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget_bid_ask.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_bid_ask.verticalHeader().setVisible(True)
        self.tableWidget_bid_ask.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget_bid_ask.verticalHeader().setMinimumSectionSize(10)
        self.verticalLayout_22.addWidget(self.tableWidget_bid_ask)
        self.horizontalLayout_31.addWidget(self.groupBox_price)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem7)
        self.verticalLayout_24.addLayout(self.horizontalLayout_31)
        self.verticalLayout_25.addLayout(self.verticalLayout_24)
        self.label_CondType.setBuddy(self.comboBox_CondType)
        self.label_ValidType.setBuddy(self.comboBox_ValidType)
        self.label_ValidTime.setBuddy(self.dateEdit_ValidTime)
        self.label_9.setBuddy(self.spinBox_StopLevel2)
        self.label_10.setBuddy(self.spinBox_toler)
        self.label_11.setBuddy(self.spinBox_trailing_stop_step)
        self.label_12.setBuddy(self.spinBox_oco_StopLevel)
        self.label_13.setBuddy(self.spinBox_oco_toler)
        self.label_14.setBuddy(self.spinBox_bullbear_profit)
        self.label_15.setBuddy(self.spinBox_bullbear_loss)
        self.label_16.setBuddy(self.spinBox_bullbear_loss_toler)
        self.label.setBuddy(self.comboBox_account)
        self.label__ProdCode.setBuddy(self.lineEdit_ProdCode)
        self.label_Price.setBuddy(self.spinBox_Price)
        self.label_Qty.setBuddy(self.spinBox_Qty)

        self.retranslateUi(Dialog_order_stoploss)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        self.radioButton_buy1.toggled['bool'].connect(self.pushButton_buy.setVisible)
        self.radioButton_sell1.toggled['bool'].connect(self.pushButton_sell.setVisible)
        self.comboBox_CondType.currentIndexChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        self.comboBox_CondType.highlighted['int'].connect(self.stackedWidget.setCurrentIndex)
        self.checkBox_Market.toggled['bool'].connect(self.checkBox_Auction.setDisabled)
        self.stackedWidget.currentChanged['int'].connect(self.comboBox_CondType.setCurrentIndex)
        self.checkBox_Auction.toggled['bool'].connect(self.checkBox_stop_tri.setDisabled)
        self.checkBox_Market.toggled['bool'].connect(self.checkBox_stop_tri.setDisabled)
        self.checkBox_stop_tri.toggled['bool'].connect(self.comboBox_StopType.setEnabled)
        self.checkBox_stop_tri.toggled['bool'].connect(self.spinBox_StopLevel.setEnabled)
        self.checkBox_stop_tri.toggled['bool'].connect(self.checkBox_Auction.setDisabled)
        self.checkBox_stop_tri.toggled['bool'].connect(self.checkBox_Market.setDisabled)
        self.checkBox_lock.toggled['bool'].connect(self.lineEdit_ProdCode.setDisabled)
        self.checkBox_Auction.toggled['bool'].connect(self.comboBox_ValidType.setDisabled)
        self.checkBox_Market.toggled['bool'].connect(self.comboBox_ValidType.setDisabled)
        self.checkBox_Market.toggled['bool'].connect(self.spinBox_market_level.setEnabled)
        self.radioButton_buy2.toggled['bool'].connect(self.pushButton_buy.setVisible)
        self.radioButton_sell2.toggled['bool'].connect(self.pushButton_sell.setVisible)
        self.checkBox_Trailing_Stop.toggled['bool'].connect(self.spinBox_trailing_stop_step.setEnabled)
        self.radioButton_buy1.toggled['bool'].connect(self.radioButton_buy2.setChecked)
        self.radioButton_sell1.toggled['bool'].connect(self.radioButton_sell2.setChecked)
        self.radioButton_buy2.toggled['bool'].connect(self.radioButton_buy1.setChecked)
        self.radioButton_sell2.toggled['bool'].connect(self.radioButton_sell1.setChecked)
        self.radioButton_buy1.toggled['bool'].connect(self.spinBox_StopLevel2.setEnabled)
        self.radioButton_buy1.toggled['bool'].connect(self.spinBox_toler.setEnabled)
        self.radioButton_sell1.toggled['bool'].connect(self.spinBox_StopLevel2.setEnabled)
        self.radioButton_sell1.toggled['bool'].connect(self.spinBox_toler.setEnabled)
        self.radioButton_buy2.toggled['bool'].connect(self.spinBox_oco_StopLevel.setEnabled)
        self.radioButton_buy2.toggled['bool'].connect(self.spinBox_oco_toler.setEnabled)
        self.radioButton_sell2.toggled['bool'].connect(self.spinBox_oco_StopLevel.setEnabled)
        self.radioButton_sell2.toggled['bool'].connect(self.spinBox_oco_toler.setEnabled)
        self.radioButton_buy1.toggled['bool'].connect(self.pushButton_sell.setHidden)
        self.radioButton_sell1.toggled['bool'].connect(self.pushButton_buy.setHidden)
        self.radioButton_buy2.toggled['bool'].connect(self.pushButton_sell.setHidden)
        self.radioButton_sell2.toggled['bool'].connect(self.pushButton_buy.setHidden)
        self.checkBox_Auction.toggled['bool'].connect(self.checkBox_Market.setDisabled)
        self.checkBox_Market.toggled['bool'].connect(self.spinBox_Price.setHidden)
        self.checkBox_Auction.toggled['bool'].connect(self.label_Price.setHidden)
        self.checkBox_Market.toggled['bool'].connect(self.label_Price.setHidden)
        self.checkBox_Market.toggled['bool'].connect(self.label_2.setVisible)
        self.checkBox_Market.toggled['bool'].connect(self.spinBox_market_level.setVisible)
        self.checkBox_Auction.toggled['bool'].connect(self.spinBox_Price.setHidden)
        self.checkBox_lock.toggled['bool'].connect(self.pushButton_buy.setEnabled)
        self.checkBox_lock.toggled['bool'].connect(self.pushButton_sell.setEnabled)
        self.checkBox_lock.toggled['bool'].connect(self.spinBox_Price.setEnabled)
        self.checkBox_lock.toggled['bool'].connect(self.radioButton_buy1.setEnabled)
        self.checkBox_lock.toggled['bool'].connect(self.radioButton_sell1.setEnabled)
        self.checkBox_lock.toggled['bool'].connect(self.radioButton_buy2.setEnabled)
        self.checkBox_lock.toggled['bool'].connect(self.radioButton_sell2.setEnabled)
        self.groupBox_price.toggled['bool'].connect(self.tableWidget_bid_ask.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Dialog_order_stoploss)
        Dialog_order_stoploss.setTabOrder(self.lineEdit_ProdCode, self.checkBox_lock)
        Dialog_order_stoploss.setTabOrder(self.checkBox_lock, self.spinBox_Price)
        Dialog_order_stoploss.setTabOrder(self.spinBox_Price, self.spinBox_Qty)
        Dialog_order_stoploss.setTabOrder(self.spinBox_Qty, self.pushButton_buy)
        Dialog_order_stoploss.setTabOrder(self.pushButton_buy, self.pushButton_sell)
        Dialog_order_stoploss.setTabOrder(self.pushButton_sell, self.comboBox_CondType)
        Dialog_order_stoploss.setTabOrder(self.comboBox_CondType, self.comboBox_ValidType)
        Dialog_order_stoploss.setTabOrder(self.comboBox_ValidType, self.dateEdit_ValidTime)
        Dialog_order_stoploss.setTabOrder(self.dateEdit_ValidTime, self.checkBox_stop_tri)
        Dialog_order_stoploss.setTabOrder(self.checkBox_stop_tri, self.spinBox_StopLevel)
        Dialog_order_stoploss.setTabOrder(self.spinBox_StopLevel, self.lineEdit_Ref)
        Dialog_order_stoploss.setTabOrder(self.lineEdit_Ref, self.checkBox_OrderOptions)
        Dialog_order_stoploss.setTabOrder(self.checkBox_OrderOptions, self.checkBox_invalid)
        Dialog_order_stoploss.setTabOrder(self.checkBox_invalid, self.checkBox_Auction)
        Dialog_order_stoploss.setTabOrder(self.checkBox_Auction, self.checkBox_Market)
        Dialog_order_stoploss.setTabOrder(self.checkBox_Market, self.radioButton_sell2)
        Dialog_order_stoploss.setTabOrder(self.radioButton_sell2, self.spinBox_oco_StopLevel)
        Dialog_order_stoploss.setTabOrder(self.spinBox_oco_StopLevel, self.spinBox_oco_toler)
        Dialog_order_stoploss.setTabOrder(self.spinBox_oco_toler, self.spinBox_market_level)
        Dialog_order_stoploss.setTabOrder(self.spinBox_market_level, self.spinBox_bullbear_profit)
        Dialog_order_stoploss.setTabOrder(self.spinBox_bullbear_profit, self.spinBox_bullbear_loss)
        Dialog_order_stoploss.setTabOrder(self.spinBox_bullbear_loss, self.spinBox_bullbear_loss_toler)
        Dialog_order_stoploss.setTabOrder(self.spinBox_bullbear_loss_toler, self.dateTimeEdit_sched_time)
        Dialog_order_stoploss.setTabOrder(self.dateTimeEdit_sched_time, self.comboBox_account)
        Dialog_order_stoploss.setTabOrder(self.comboBox_account, self.radioButton_sell1)
        Dialog_order_stoploss.setTabOrder(self.radioButton_sell1, self.spinBox_StopLevel2)
        Dialog_order_stoploss.setTabOrder(self.spinBox_StopLevel2, self.spinBox_toler)
        Dialog_order_stoploss.setTabOrder(self.spinBox_toler, self.spinBox_trailing_stop_step)
        Dialog_order_stoploss.setTabOrder(self.spinBox_trailing_stop_step, self.radioButton_buy2)
        Dialog_order_stoploss.setTabOrder(self.radioButton_buy2, self.checkBox_Trailing_Stop)
        Dialog_order_stoploss.setTabOrder(self.checkBox_Trailing_Stop, self.comboBox_StopType)
        Dialog_order_stoploss.setTabOrder(self.comboBox_StopType, self.radioButton_buy1)

    def retranslateUi(self, Dialog_order_stoploss):
        _translate = QtCore.QCoreApplication.translate
        Dialog_order_stoploss.setWindowTitle(_translate("Dialog_order_stoploss", "SP  ORDER STOPLOSS"))
        self.label_CondType.setText(_translate("Dialog_order_stoploss", "条件"))
        self.comboBox_CondType.setItemText(0, _translate("Dialog_order_stoploss", "普通指令"))
        self.comboBox_CondType.setItemText(1, _translate("Dialog_order_stoploss", "止损指令"))
        self.comboBox_CondType.setItemText(2, _translate("Dialog_order_stoploss", "双向限价"))
        self.comboBox_CondType.setItemText(3, _translate("Dialog_order_stoploss", "牛市熊市"))
        self.comboBox_CondType.setItemText(4, _translate("Dialog_order_stoploss", "预订指令"))
        self.groupBox.setTitle(_translate("Dialog_order_stoploss", "有效期"))
        self.label_ValidType.setText(_translate("Dialog_order_stoploss", "类型"))
        self.comboBox_ValidType.setItemText(0, _translate("Dialog_order_stoploss", "即日"))
        self.comboBox_ValidType.setItemText(1, _translate("Dialog_order_stoploss", "成交并取消"))
        self.comboBox_ValidType.setItemText(2, _translate("Dialog_order_stoploss", "成交或取消"))
        self.comboBox_ValidType.setItemText(3, _translate("Dialog_order_stoploss", "到期日"))
        self.comboBox_ValidType.setItemText(4, _translate("Dialog_order_stoploss", "指定日期"))
        self.label_ValidTime.setText(_translate("Dialog_order_stoploss", "日期"))
        self.dateEdit_ValidTime.setDisplayFormat(_translate("Dialog_order_stoploss", "yyyy/M/d"))
        self.checkBox_stop_tri.setText(_translate("Dialog_order_stoploss", " 止损/触发"))
        self.comboBox_StopType.setItemText(0, _translate("Dialog_order_stoploss", "限止"))
        self.comboBox_StopType.setItemText(1, _translate("Dialog_order_stoploss", "升市"))
        self.comboBox_StopType.setItemText(2, _translate("Dialog_order_stoploss", "跌市"))
        self.comboBox_StopType.setItemText(3, _translate("Dialog_order_stoploss", "市止"))
        self.radioButton_buy1.setText(_translate("Dialog_order_stoploss", "买入"))
        self.radioButton_sell1.setText(_translate("Dialog_order_stoploss", "沽出"))
        self.label_9.setText(_translate("Dialog_order_stoploss", "止损价"))
        self.label_10.setText(_translate("Dialog_order_stoploss", "追价"))
        self.checkBox_Trailing_Stop.setText(_translate("Dialog_order_stoploss", "追踪止损"))
        self.label_11.setText(_translate("Dialog_order_stoploss", "梯级"))
        self.radioButton_buy2.setText(_translate("Dialog_order_stoploss", "买入"))
        self.radioButton_sell2.setText(_translate("Dialog_order_stoploss", "沽出"))
        self.label_12.setText(_translate("Dialog_order_stoploss", "限价止损"))
        self.label_13.setText(_translate("Dialog_order_stoploss", "追价"))
        self.label_2.setText(_translate("Dialog_order_stoploss", "市价追价"))
        self.label_14.setText(_translate("Dialog_order_stoploss", "止赚"))
        self.label_15.setText(_translate("Dialog_order_stoploss", "止损"))
        self.label_16.setText(_translate("Dialog_order_stoploss", "止损追价"))
        self.dateTimeEdit_sched_time.setDisplayFormat(_translate("Dialog_order_stoploss", "M/d dddd H:mm"))
        self.label.setText(_translate("Dialog_order_stoploss", "账户"))
        self.label__ProdCode.setText(_translate("Dialog_order_stoploss", "代码"))
        self.checkBox_lock.setText(_translate("Dialog_order_stoploss", "锁定"))
        self.label_Price.setText(_translate("Dialog_order_stoploss", "价格"))
        self.checkBox_Auction.setText(_translate("Dialog_order_stoploss", "竞价"))
        self.checkBox_Market.setText(_translate("Dialog_order_stoploss", "市价"))
        self.label_Qty.setText(_translate("Dialog_order_stoploss", "数量"))
        self.pushButton_buy.setText(_translate("Dialog_order_stoploss", "买入"))
        self.pushButton_sell.setText(_translate("Dialog_order_stoploss", "沽出"))
        self.label_Ref.setText(_translate("Dialog_order_stoploss", "参考"))
        self.checkBox_OrderOptions.setText(_translate("Dialog_order_stoploss", "T+1"))
        self.checkBox_invalid.setText(_translate("Dialog_order_stoploss", "无效"))
        self.checkBox_order_assistant.setText(_translate("Dialog_order_stoploss", "下单辅助"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog_order_stoploss", "下单"))
        self.label_7.setText(_translate("Dialog_order_stoploss", "代码："))
        self.groupBox_quick_sl.setTitle(_translate("Dialog_order_stoploss", "-@-"))
        self.label_3.setText(_translate("Dialog_order_stoploss", "持仓成本"))
        self.label_4.setText(_translate("Dialog_order_stoploss", "会话成本"))
        self.label_5.setText(_translate("Dialog_order_stoploss", "  总成本"))
        self.label_6.setText(_translate("Dialog_order_stoploss", "追价点位"))
        self.label_8.setText(_translate("Dialog_order_stoploss", "止损点位"))
        self.label_17.setText(_translate("Dialog_order_stoploss", "锁单数"))
        self.pushButton_stoploss.setText(_translate("Dialog_order_stoploss", "止损"))
        self.pushButton_del_all_orders.setText(_translate("Dialog_order_stoploss", "删除未成交单"))
        self.pushButton_del_long_sl.setText(_translate("Dialog_order_stoploss", "删除止损多单"))
        self.pushButton_del_short_sl.setText(_translate("Dialog_order_stoploss", "删除止损空单"))
        self.pushButton_del_remain_sl.setText(_translate("Dialog_order_stoploss", "删除多余止损单"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog_order_stoploss", "快速止损"))
        self.groupBox_price.setTitle(_translate("Dialog_order_stoploss", "报价"))
        item = self.tableWidget_bid_ask.verticalHeaderItem(0)
        item.setText(_translate("Dialog_order_stoploss", "卖⑤"))
        item = self.tableWidget_bid_ask.verticalHeaderItem(1)
        item.setText(_translate("Dialog_order_stoploss", "卖④"))
        item = self.tableWidget_bid_ask.verticalHeaderItem(2)
        item.setText(_translate("Dialog_order_stoploss", "卖③"))
        item = self.tableWidget_bid_ask.verticalHeaderItem(3)
        item.setText(_translate("Dialog_order_stoploss", "卖②"))
        item = self.tableWidget_bid_ask.verticalHeaderItem(4)
        item.setText(_translate("Dialog_order_stoploss", "卖①"))
        item = self.tableWidget_bid_ask.verticalHeaderItem(5)
        item.setText(_translate("Dialog_order_stoploss", "买①"))
        item = self.tableWidget_bid_ask.verticalHeaderItem(6)
        item.setText(_translate("Dialog_order_stoploss", "买②"))
        item = self.tableWidget_bid_ask.verticalHeaderItem(7)
        item.setText(_translate("Dialog_order_stoploss", "买③"))
        item = self.tableWidget_bid_ask.verticalHeaderItem(8)
        item.setText(_translate("Dialog_order_stoploss", "买④"))
        item = self.tableWidget_bid_ask.verticalHeaderItem(9)
        item.setText(_translate("Dialog_order_stoploss", "买⑤"))

