# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'order_comfirm_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_order_comfirm(object):
    def setupUi(self, Dialog_order_comfirm):
        Dialog_order_comfirm.setObjectName("Dialog_order_comfirm")
        Dialog_order_comfirm.resize(178, 255)
        self.gridLayout = QtWidgets.QGridLayout(Dialog_order_comfirm)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_subtitle = QtWidgets.QLabel(Dialog_order_comfirm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_subtitle.sizePolicy().hasHeightForWidth())
        self.label_subtitle.setSizePolicy(sizePolicy)
        self.label_subtitle.setObjectName("label_subtitle")
        self.verticalLayout_3.addWidget(self.label_subtitle)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(Dialog_order_comfirm)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_BuySell = QtWidgets.QLabel(Dialog_order_comfirm)
        self.label_BuySell.setObjectName("label_BuySell")
        self.horizontalLayout_2.addWidget(self.label_BuySell)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(Dialog_order_comfirm)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_ProdCode = QtWidgets.QLabel(Dialog_order_comfirm)
        self.label_ProdCode.setObjectName("label_ProdCode")
        self.horizontalLayout_3.addWidget(self.label_ProdCode)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(Dialog_order_comfirm)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_Price = QtWidgets.QLabel(Dialog_order_comfirm)
        self.label_Price.setObjectName("label_Price")
        self.horizontalLayout_4.addWidget(self.label_Price)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(Dialog_order_comfirm)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.label_Qty = QtWidgets.QLabel(Dialog_order_comfirm)
        self.label_Qty.setObjectName("label_Qty")
        self.horizontalLayout_5.addWidget(self.label_Qty)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(Dialog_order_comfirm)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.label_Cond = QtWidgets.QLabel(Dialog_order_comfirm)
        self.label_Cond.setObjectName("label_Cond")
        self.horizontalLayout_6.addWidget(self.label_Cond)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(Dialog_order_comfirm)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.label_VaildTime = QtWidgets.QLabel(Dialog_order_comfirm)
        self.label_VaildTime.setObjectName("label_VaildTime")
        self.horizontalLayout_7.addWidget(self.label_VaildTime)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox_comfirm = QtWidgets.QDialogButtonBox(Dialog_order_comfirm)
        self.buttonBox_comfirm.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_comfirm.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox_comfirm.setObjectName("buttonBox_comfirm")
        self.verticalLayout_2.addWidget(self.buttonBox_comfirm)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Dialog_order_comfirm)
        self.buttonBox_comfirm.accepted.connect(Dialog_order_comfirm.accept)
        self.buttonBox_comfirm.rejected.connect(Dialog_order_comfirm.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_order_comfirm)

    def retranslateUi(self, Dialog_order_comfirm):
        _translate = QtCore.QCoreApplication.translate
        Dialog_order_comfirm.setWindowTitle(_translate("Dialog_order_comfirm", "指示确认"))
        self.label_subtitle.setText(_translate("Dialog_order_comfirm", "新增指示"))
        self.label_3.setText(_translate("Dialog_order_comfirm", "指令："))
        self.label_BuySell.setText(_translate("Dialog_order_comfirm", "buysell"))
        self.label_4.setText(_translate("Dialog_order_comfirm", "代号："))
        self.label_ProdCode.setText(_translate("Dialog_order_comfirm", "prodcode"))
        self.label_5.setText(_translate("Dialog_order_comfirm", "价格："))
        self.label_Price.setText(_translate("Dialog_order_comfirm", "price"))
        self.label_6.setText(_translate("Dialog_order_comfirm", "数量："))
        self.label_Qty.setText(_translate("Dialog_order_comfirm", "qty"))
        self.label_7.setText(_translate("Dialog_order_comfirm", "条件："))
        self.label_Cond.setText(_translate("Dialog_order_comfirm", "cond"))
        self.label_8.setText(_translate("Dialog_order_comfirm", "有效期："))
        self.label_VaildTime.setText(_translate("Dialog_order_comfirm", "vaildtime"))

