# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sp_login.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_sp_login(object):
    def setupUi(self, Dialog_sp_login):
        Dialog_sp_login.setObjectName("Dialog_sp_login")
        Dialog_sp_login.resize(240, 320)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_sp_login)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_host = QtWidgets.QLabel(Dialog_sp_login)
        self.label_host.setObjectName("label_host")
        self.horizontalLayout.addWidget(self.label_host)
        self.lineEdit_host = QtWidgets.QLineEdit(Dialog_sp_login)
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.horizontalLayout.addWidget(self.lineEdit_host)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_port = QtWidgets.QLabel(Dialog_sp_login)
        self.label_port.setObjectName("label_port")
        self.horizontalLayout_2.addWidget(self.label_port)
        self.lineEdit_port = QtWidgets.QLineEdit(Dialog_sp_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_port.sizePolicy().hasHeightForWidth())
        self.lineEdit_port.setSizePolicy(sizePolicy)
        self.lineEdit_port.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.horizontalLayout_2.addWidget(self.lineEdit_port)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_license = QtWidgets.QLabel(Dialog_sp_login)
        self.label_license.setObjectName("label_license")
        self.horizontalLayout_3.addWidget(self.label_license)
        self.lineEdit_license = QtWidgets.QLineEdit(Dialog_sp_login)
        self.lineEdit_license.setObjectName("lineEdit_license")
        self.horizontalLayout_3.addWidget(self.lineEdit_license)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_app_id = QtWidgets.QLabel(Dialog_sp_login)
        self.label_app_id.setObjectName("label_app_id")
        self.horizontalLayout_4.addWidget(self.label_app_id)
        self.lineEdit_app_id = QtWidgets.QLineEdit(Dialog_sp_login)
        self.lineEdit_app_id.setObjectName("lineEdit_app_id")
        self.horizontalLayout_4.addWidget(self.lineEdit_app_id)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_user_id = QtWidgets.QLabel(Dialog_sp_login)
        self.label_user_id.setObjectName("label_user_id")
        self.horizontalLayout_5.addWidget(self.label_user_id)
        self.lineEdit_user_id = QtWidgets.QLineEdit(Dialog_sp_login)
        self.lineEdit_user_id.setObjectName("lineEdit_user_id")
        self.horizontalLayout_5.addWidget(self.lineEdit_user_id)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_password = QtWidgets.QLabel(Dialog_sp_login)
        self.label_password.setObjectName("label_password")
        self.horizontalLayout_6.addWidget(self.label_password)
        self.lineEdit_password = QtWidgets.QLineEdit(Dialog_sp_login)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_6.addWidget(self.lineEdit_password)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_sp_login)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.label_host.setBuddy(self.lineEdit_host)
        self.label_port.setBuddy(self.lineEdit_port)
        self.label_license.setBuddy(self.lineEdit_license)
        self.label_app_id.setBuddy(self.lineEdit_app_id)
        self.label_user_id.setBuddy(self.lineEdit_user_id)
        self.label_password.setBuddy(self.lineEdit_password)

        self.retranslateUi(Dialog_sp_login)
        self.buttonBox.accepted.connect(Dialog_sp_login.accept)
        self.buttonBox.rejected.connect(Dialog_sp_login.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_sp_login)

    def retranslateUi(self, Dialog_sp_login):
        _translate = QtCore.QCoreApplication.translate
        Dialog_sp_login.setWindowTitle(_translate("Dialog_sp_login", "SP_LOGIN"))
        self.label_host.setText(_translate("Dialog_sp_login", "Host"))
        self.lineEdit_host.setText(_translate("Dialog_sp_login", "demo.spsystem1.info"))
        self.label_port.setText(_translate("Dialog_sp_login", "Port"))
        self.lineEdit_port.setText(_translate("Dialog_sp_login", "8080"))
        self.label_license.setText(_translate("Dialog_sp_login", "License"))
        self.lineEdit_license.setText(_translate("Dialog_sp_login", "59493B8B4C09F"))
        self.label_app_id.setText(_translate("Dialog_sp_login", "app_id"))
        self.lineEdit_app_id.setText(_translate("Dialog_sp_login", "SPDEMO"))
        self.label_user_id.setText(_translate("Dialog_sp_login", "user_id"))
        self.lineEdit_user_id.setText(_translate("Dialog_sp_login", "DEMO201706051A"))
        self.label_password.setText(_translate("Dialog_sp_login", "password"))
        self.lineEdit_password.setText(_translate("Dialog_sp_login", "1234"))

